# author: ddukic

ACE_TRIGGERS = [
    "Business:Merge-Org",
    "Business:Start-Org",
    "Business:Declare-Bankruptcy",
    "Business:End-Org",
    "Justice:Pardon",
    "Justice:Extradite",
    "Justice:Execute",
    "Justice:Fine",
    "Justice:Trial-Hearing",
    "Justice:Sentence",
    "Justice:Appeal",
    "Justice:Convict",
    "Justice:Sue",
    "Justice:Release-Parole",
    "Justice:Arrest-Jail",
    "Justice:Charge-Indict",
    "Justice:Acquit",
    "Conflict:Demonstrate",
    "Conflict:Attack",
    "Contact:Phone-Write",
    "Contact:Meet",
    "Personnel:Start-Position",
    "Personnel:Elect",
    "Personnel:End-Position",
    "Personnel:Nominate",
    "Transaction:Transfer-Ownership",
    "Transaction:Transfer-Money",
    "Life:Marry",
    "Life:Divorce",
    "Life:Be-Born",
    "Life:Die",
    "Life:Injure",
    "Movement:Transport",
]

ACE_TRIGGERS_TO_OPTIONS = {
    "Business:Merge-Org": "Merge Organization",
    "Business:Start-Org": "Start Organization",
    "Business:Declare-Bankruptcy": "Declare Bankruptcy",
    "Business:End-Org": "End Organization",
    "Justice:Pardon": "Grant Pardon",
    "Justice:Extradite": "Extradite",
    "Justice:Execute": "Execute",
    "Justice:Fine": "Impose Fine",
    "Justice:Trial-Hearing": "Conduct Trial Hearing",
    "Justice:Sentence": "Issue Sentence",
    "Justice:Appeal": "File Appeal",
    "Justice:Convict": "Convict",
    "Justice:Sue": "File Lawsuit",
    "Justice:Release-Parole": "Release on Parole",
    "Justice:Arrest-Jail": "Arrest and Send to Jail",
    "Justice:Charge-Indict": "Charge and Indict",
    "Justice:Acquit": "Acquit",
    "Conflict:Demonstrate": "Participate in protest or demonstration",
    "Conflict:Attack": "Attack",
    "Contact:Phone-Write": "Contact via written or telephone communication",
    "Contact:Meet": "Meet",
    "Personnel:Start-Position": "Start Position",
    "Personnel:Elect": "Elect",
    "Personnel:End-Position": "End Position",
    "Personnel:Nominate": "Nominate",
    "Transaction:Transfer-Ownership": "Transfer Ownership",
    "Transaction:Transfer-Money": "Transfer Money",
    "Life:Marry": "Marry",
    "Life:Divorce": "Divorce",
    "Life:Be-Born": "Be Born",
    "Life:Die": "Die",
    "Life:Injure": "Sustain Injury",
    "Movement:Transport": "Transport",
}

REPO_HOME = "/lustre/home/ddukic/generative-ie/"
